Repository APPS-sookmyung/2024-APPS-Exhibition-Webpage, pull requests merged in 2024-12, with the labels that each got.

#85 #84 [DESIGN] About 페이지 반응형 수정
  src/components/ActivityCard/ActivityCard.jsx
  src/components/ActivityCard/ActivityCard.style.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: 🎨 UI

#90 #86 [FEAT] SNS 새 창 열기 속성 적용
  src/components/SocialMediaLinkCards/SocialMediaLinkCards.jsx
Labels: ✨ Feature

#93 #92 [FEAT] 링크 공유하기 버튼 클릭시 링크 복사되는 기능 구현
  src/pages/HomePage/HomePage.jsx
Labels: ✨ Feature

#103 #89 [FIX] 폰트 적용
  public/fonts/woff/Pretendard-Black.woff
  public/fonts/woff/Pretendard-Bold.woff
  public/fonts/woff/Pretendard-ExtraBold.woff
  public/fonts/woff/Pretendard-ExtraLight.woff
  public/fonts/woff/Pretendard-Light.woff
  public/fonts/woff/Pretendard-Medium.woff
  public/fonts/woff/Pretendard-Regular.woff
  public/fonts/woff/Pretendard-SemiBold.woff
  public/fonts/woff/Pretendard-Thin.woff
  public/fonts/woff2/Pretendard-Black.woff2
  public/fonts/woff2/Pretendard-Bold.woff2
  public/fonts/woff2/Pretendard-ExtraBold.woff2
  public/fonts/woff2/Pretendard-ExtraLight.woff2
  public/fonts/woff2/Pretendard-Light.woff2
  public/fonts/woff2/Pretendard-Medium.woff2
  public/fonts/woff2/Pretendard-Regular.woff2
  public/fonts/woff2/Pretendard-SemiBold.woff2
  public/fonts/woff2/Pretendard-Thin.woff2
  src/App.js
  src/index.js
  src/styles/exhibitionStyles.style.js
  src/styles/index.js
Labels: 🔧 Fix

#107 #104 [FEAT] 앱스 핵심 코어 영역 해시태그 줄바꿈 적용
  src/components/AboutAppsCoreValueCard/AboutAppsCoreValueCard.jsx
  src/components/AboutAppsCoreValueCard/AboutAppsCoreValueCard.style.jsx
  src/database/appsCoreValueCards.js
  src/pages/HomePage/HomePage.jsx
Labels: ✨ Feature

#110 #106 [FEAT] Dolce Vita 폰트 적용
  public/fonts/woff/dolce-vita-heavy-bold.woff
  public/fonts/woff/dolce-vita-light.woff
  public/fonts/woff/dolce-vita.woff
  src/index.js
  src/styles/DolceVitaFont.style.jsx
  src/styles/GlobalStyle.style.jsx
  src/styles/index.js
Labels: 🎨 UI

#101 #98 [FEAT] About 페이지 상단 모션 반응형 수정
  src/components/ActivityCard/ActivityCard.jsx
  src/components/ActivityCard/ActivityCard.style.jsx
  src/components/CalendarCard/CalendarCard.jsx
  src/components/CalendarCard/CalendarCard.style.jsx
  src/components/FallingBlocks/FallingBlocks.jsx
  src/components/FallingBlocks/FallingBlocks.style.jsx
  src/database/styledSquareColorCards.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: ✨ Feature, 🎨 UI

#113 #112 [FEAT] 멤버 이미지 정렬 재수정
  src/components/MemberCard/MemberCard.style.jsx
Labels: ✨ Feature

#115 #111 [FIX] 활동 카드 내 글자 넘침 이슈와 APPS 상단에 파란 블록 화면에 고정되는 이슈 해결
  src/components/ActivityCard/ActivityCard.jsx
  src/components/ActivityCard/ActivityCard.style.jsx
  src/styles/exhibitionStyles.style.js
Labels: 🔧 Fix

#117 #116 [FIX] SNS 이미지 가운데 정렬
  src/components/SocialMediaLinkCards/SocialMediaLinkCards.style.jsx
Labels: 🔧 Fix

#121 #97 [FEAT] 프로젝트 페이지: 개발자, 회고, 프로젝트 더보기 항목 추가
  public/images/thumbnails/img-thumbnail-1-sample.png
  public/images/thumbnails/img-thumbnail-1.png
  public/images/thumbnails/img-thumbnail-2.png
  public/images/thumbnails/img-thumbnail-3.png
  public/images/thumbnails/img-thumbnail-4.png
  public/images/thumbnails/img-thumbnail-5.png
  public/images/thumbnails/img-thumbnail-6.png
  src/components/DeveloperCard/DeveloperCard.jsx
  src/components/DeveloperCard/DeveloperCard.style.jsx
  src/components/DeveloperCard/index.js
  src/components/ProjectRecommend/ProjectRecommend.jsx
  src/components/ProjectRecommend/ProjectRecommend.style.jsx
  src/components/ProjectRecommend/index.js
  src/components/ReviewCard/ReviewCard.jsx
  src/components/ReviewCard/ReviewCard.style.jsx
  src/components/ReviewCard/index.js
  src/components/index.js
  src/database/developers.js
  src/database/index.js
  src/database/projectRecommend.js
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: ✨ Feature

#126 #125 [FEAT] 프로젝트 페이지: 디테일 수정
  src/components/ReviewCard/ReviewCard.style.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: ✨ Feature

#127 #108 [FEAT] 홈페이지 상하단 배경에 반응형 적용
  public/images/background/home-background-1.svg
  public/images/background/home-background-2.svg
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: 🎨 UI

#131 #129 [FEAT] 프로젝트 라우터 연결
  public/images/background/home-background-bottom.svg
  public/images/background/home-background-top.svg
  public/images/background/home-background.svg
  src/components/ProjectCardList/ProjectCardList.jsx
  src/database/projectList.js
  src/pages/HomePage/HomePage.style.jsx
  src/router.jsx
Labels: ✨ Feature

#133 [MERGE] dev to main
  public/images/background/home-background-bottom.svg
  public/images/background/home-background-top.svg
  public/images/background/home-background.svg
  public/images/techStacks/apache.png
  public/images/techStacks/cra.svg
  public/images/techStacks/css.png
  public/images/techStacks/dart.svg
  public/images/techStacks/docker.png
  public/images/techStacks/flutter.png
  public/images/techStacks/github-actions.png
  public/images/techStacks/gradle.png
  public/images/techStacks/html.png
  public/images/techStacks/javascript.png
  public/images/techStacks/mysql.png
  public/images/techStacks/naver-clova-ocr.svg
  public/images/techStacks/netlify.png
  public/images/techStacks/nginx.svg
  public/images/techStacks/npm.png
  public/images/techStacks/oauth2.png
  public/images/techStacks/spring-boot.png
  public/images/techStacks/spring-data-jpa.png
  public/images/techStacks/styled-components.png
  public/images/techStacks/swiftui.png
  public/images/techStacks/tailwindcss.png
  public/images/techStacks/typescript.png
  public/images/thumbnails/birthdaybuddy.png
  public/images/thumbnails/bookmemories.png
  public/images/thumbnails/cookiee-.png
  public/images/thumbnails/emotion.png
  public/images/thumbnails/greentalk.png
  public/images/thumbnails/hereandthere.png
  public/images/thumbnails/juryangdo.png
  public/images/thumbnails/merry-tree.png
  public/images/thumbnails/pettory.png
  public/images/thumbnails/sookmechu-real.jpg
  public/images/thumbnails/stattracker.png
  public/images/thumbnails/studypage.jpg
  public/images/thumbnails/studytracker.png
  public/images/thumbnails/wellet.png
  src/components/ActivityCard/ActivityCard.style.jsx
  src/components/CalendarCard/CalendarCard.style.jsx
  src/components/FallingBlocks/FallingBlocks.style.jsx
  src/components/MemberCard/MemberCard.jsx
  src/components/MemberCard/MemberCard.style.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/ProjectCardList/ProjectCardList.jsx
  src/components/ReviewCard/ReviewCard.style.jsx
  src/database/activityCardList.js
  src/database/projectList.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
  src/router.jsx
Labels: 🌏 Deploy

#140 #138 [FIX] 홈 화면 내 상단 배경화면 반응형 재적용
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: 🎨 UI

#145 #141 [FIX] 프로젝트 카드 높이가 영역안에서 최대가 되도록 수정
  src/components/ProjectCardList/ProjectCardList.jsx
  src/components/ProjectCardList/ProjectCardList.style.jsx
Labels: 🔧 Fix

#152 #136 [FIX] 모달 디테일 수정
  src/components/Modal/Modal.style.jsx
Labels: 🔧 Fix

#154 #153 [FIX] 모달 밖 스크롤 방지
  src/components/Modal/Modal.jsx
Labels: 🔧 Fix

#158 #155 [FEAT] 디자이너 프로필 추가
  public/images/memberProfiles/kimsoojin.png
  public/images/memberProfiles/moonseoyoung.png
  public/images/memberProfiles/ryumisung.png
  src/database/projectList.js
Labels: ✨ Feature

#161 #159 [DESIGN] 서브 내용의 폰트 컬러 변경 및 프로젝트 데이터 일부 수정
  src/components/DeveloperCard/DeveloperCard.style.jsx
  src/components/ReviewCard/ReviewCard.style.jsx
  src/database/projectList.js
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: 🪄 Modify, 🎨 UI

#164 #162 [FEAT] X 버튼 클릭시 홈화면의 프로젝트 목록 섹션으로 이동
  src/components/Header/Header.jsx
  src/components/ProjectCardList/ProjectCardList.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ProjectPage/ProjectPage.jsx
Labels: ✨ Feature

#165 [MERGE] dev to main
  public/images/memberProfiles/kimsoojin.png
  public/images/memberProfiles/moonseoyoung.png
  public/images/memberProfiles/ryumisung.png
  src/components/DeveloperCard/DeveloperCard.style.jsx
  src/components/Header/Header.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/ProjectCardList/ProjectCardList.style.jsx
  src/components/ReviewCard/ReviewCard.style.jsx
  src/database/projectList.js
  src/pages/HomePage/HomePage.jsx
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: 🌏 Deploy

#167 #166 [FEAT] 폰트 적용 및 프로젝트 공유하기 버튼 높이 수정
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: ✨ Feature

#168 #87 [FEAT] 부원들이 말하는 APPS 움직이는 모션 구현
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.jsx
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.style.jsx
  src/database/memberFeedback.js
  src/database/projectList.js
  src/pages/HomePage/HomePage.jsx
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: ✨ Feature

#169 #163 [FIX] 모달 내 선 반응형 수정
  public/images/icons/divider.svg
  src/components/Modal/Modal.style.jsx
Labels: 🔧 Fix

#171 #170 [FEAT] 홈화면 내 전시 글자 옆에 화살표 이미지 적용
  public/images/icons/icon-arrow-top-right.svg
  public/images/logo/logo-pink.svg
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#172 #160 [FEAT] 페이지 이동 시 맨 위로 위치하기 구현
  src/components/ScrollToTop/ScrollToTop.jsx
  src/router.jsx
  src/styles/exhibitionStyles.style.js
Labels: ✨ Feature

#173 [MERGE] dev to main
  public/images/icons/divider.svg
  public/images/icons/icon-arrow-top-right.svg
  public/images/logo/logo-pink.svg
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.jsx
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.style.jsx
  src/components/Modal/Modal.style.jsx
  src/components/ScrollToTop/ScrollToTop.jsx
  src/database/memberFeedback.js
  src/database/projectList.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
  src/router.jsx
  src/styles/exhibitionStyles.style.js
Labels: 🌏 Deploy

#175 #174 [FEAT] 프로젝트 공유하기 이름 변경 및 호버 효과 적용
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: ✨ Feature

#177 #176 [REMOVE] 프로젝트 페이지 `DeveloperCard` 커서 삭제
  src/components/DeveloperCard/DeveloperCard.style.jsx
Labels: 🎨 UI

#181 #180 [FIX] 닫기 버튼 클릭 시 홈 화면 맨 위로 돌아감 이슈 해결
  src/pages/HomePage/HomePage.jsx
Labels: 🔧 Fix

#182 [MERGE] dev to main
  public/images/memberProfiles/hwangsuyeon.jpg
  public/images/memberProfiles/joyeongseo.jpg
  public/images/thumbnails/birthdaybuddy.png
  public/images/thumbnails/emotion.jpg
  public/images/thumbnails/emotion.png
  public/images/thumbnails/outfoot.png
  src/components/DeveloperCard/DeveloperCard.style.jsx
  src/database/projectList.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: 🌏 Deploy

#184 #183 [FEAT] 멤버 회고 수정
  src/database/members.js
Labels: ✨ Feature

#185 [MERGE] dev to main
  src/database/members.js
Labels: 🌏 Deploy

#187 #186 [MODIFY] 유튜브 링크, 프로필 이미지 등 데이터 수정
  public/images/memberProfiles/kimsoojin.png
  public/images/thumbnails/cagongdo.png
  public/images/thumbnails/wellet.png
  src/database/projectList.js
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: 🪄 Modify

#188 #186 [MODIFY] 데이터 일부 변경
  src/database/projectList.js
  src/pages/ProjectPage/ProjectPage.jsx
Labels: 🪄 Modify

#190 #189 [FEAT] 카공도 회고 및 유튜브 링크 추가
  src/database/projectList.js
Labels: ✨ Feature

#193 [MERGE] dev to main
  public/images/memberProfiles/kimsoojin.png
  public/images/thumbnails/cagongdo.png
  public/images/thumbnails/wellet.png
  src/database/projectList.js
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: 🌏 Deploy

#196 #194 [FIX] 유튜브 URL 변경
  src/database/projectList.js
Labels: 🔧 Fix

#195 #191 [FIX] Safari에서 프로젝트 카드 비율 깨짐 오류 해결
  src/components/ProjectCardList/ProjectCardList.style.jsx
Labels: 🔧 Fix

#197 [MERGE] dev to main
  src/components/ProjectCardList/ProjectCardList.style.jsx
  src/database/projectList.js
Labels: 🌏 Deploy

#198 #194 [FIX] 유튜브 URL 변경
  src/database/projectList.js
Labels: 🔧 Fix

#199 [MERGE] dev to main
  src/database/projectList.js
Labels: 🌏 Deploy

#200 #194 [FIX] 유튜브 URL 변경
  src/database/projectList.js
Labels: 🔧 Fix

#201 [MERGE] dev to main
  src/database/projectList.js
Labels: 🌏 Deploy

#203 #202 [FEAT] 구글 애널리틱스 코드 추가
  public/index.html
Labels: ✨ Feature

#204 [MERGE] dev to main
  public/index.html
Labels: 🌏 Deploy

#207 #206 [FEAT] projectList 일부 수정
  public/images/memberProfiles/kimhaejoo.png
  src/database/projectList.js
Labels: ✨ Feature

#208 [MERGE] dev to main
  public/images/memberProfiles/kimhaejoo.png
  src/database/projectList.js
Labels: 🌏 Deploy
