Repository APPS-sookmyung/2024-APPS-Exhibition-Webpage, pull requests merged in 2024-11, with the labels that each got.

#2 #1 [DOCS] README 문서 작성
  README.md
Labels: 📄 Docs

#3 #1 [DOCS] issue, PR 템플릿 생성
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: 📄 Docs

#5 #4 [FEAT] .gitignore 파일 생성
  .gitignore
Labels: ⚙️ Setting

#6 #4 [FEAT] 프로젝트 기본 세팅
  .gitignore
  .prettierrc.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  yarn.lock
Labels: ⚙️ Setting

#8 #7 [FEAT] 프로젝트 기본 세팅
  .prettierrc.json
  package.json
  public/apps-logo.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.js
  src/components/.gitkeep
  src/database/.gitkeep
  src/images/memberProfiles/ryumisung.png
  src/images/socials/app-store.svg
  src/images/socials/github.svg
  src/images/socials/linkedin.svg
  src/images/socials/tstory.svg
  src/images/socials/velog.svg
  src/images/socials/webpage-link.svg
  src/images/techStacks/aws.png
  src/images/techStacks/react.png
  src/images/thumbnails/sample.png
  src/index.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
  src/pages/AboutAppsPage/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/HomePage/index.js
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
  src/pages/ProjectPage/index.js
  src/pages/index.js
  src/router.jsx
  src/styles/GlobalStyle.style.jsx
  src/styles/PretendardFont.style.jsx
  src/styles/exhibitionStyles.style.js
  src/styles/index.js
  src/styles/mediaQueries.style.js
  src/styles/resetStyles.style.js
  yarn.lock
Labels: ⚙️ Setting

#13 #12 [FEAT] AboutPage 상단 코드 일부 작성
  src/images/background/about_background.svg
  src/images/icons/about_APPS.svg
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: ✨ Feature

#15 #14 [FEAT] About 페이지 소개 부분 구현
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: ✨ Feature

#25 #24 [DESIGN] header 디테일 수정
  src/components/Header/Header.jsx
  src/components/Header/Header.style.jsx
Labels: 🎨 UI

#27 #26 [FEAT] 홈화면 일부 구현
  public/images/background/home-background1.svg
  public/images/background/home-background2.svg
  public/images/logo/logo-apps.png
  public/images/logo/logo-white.svg
  public/images/techStacks/aws.png
  public/images/techStacks/react.png
  public/images/thumbnails/sample.png
  public/index.html
  src/components/Header/Header.jsx
  src/components/PageLayout/PageLayout.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#29 #28 [FEAT] About 페이지 달력 부분 구현
  public/images/activities/about_BSproject.jpg
  public/images/activities/about_DevTalk.jpg
  public/images/activities/about_MT.jpg
  public/images/activities/about_basicstudy.jpg
  public/images/activities/about_exhibition.jpg
  public/images/activities/about_normalstudy.jpg
  public/images/activities/about_picnic.jpg
  public/images/activities/about_teamproject.jpg
  public/images/background/about_background.svg
  public/images/icons/about_APPS.svg
  public/images/icons/about_calendar_blue_dot.svg
  public/images/icons/about_calendar_white_dot.svg
  src/components/CalendarCard/CalendarCard.jsx
  src/components/CalendarCard/CalendarCard.style.jsx
  src/database/activity_list.js
  src/database/calendar_list.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: ✨ Feature

#35 #31 [FEAT] 프로젝트 페이지 - 세부정보 UI 구현 & 반응형 설정
  public/images/background/projects_background.svg
  public/images/background/projects_line.svg
  public/images/icons/share.svg
  public/images/icons/x_pink.svg
  public/images/socials/app-store.svg
  public/images/socials/github.svg
  public/images/socials/index.js
  public/images/socials/linkedin.svg
  public/images/socials/tstory.svg
  public/images/socials/velog.svg
  public/images/socials/webpage-link.svg
  public/images/techStacks/firebase.svg
  public/images/techStacks/nextjs.svg
  src/images/socials/webpage-link.svg
  src/pages/ProjectPage/ProjectPage.jsx
  src/pages/ProjectPage/ProjectPage.style.jsx
Labels: ✨ Feature

#36 #33 [FEAT] About APPS 섹션 구현
  public/images/icons/icon-with-A.svg
  public/images/icons/icon-with-P-green.svg
  public/images/icons/icon-with-P-orange.svg
  public/images/icons/icon-with-S.svg
  public/images/logo/logo-gradation.svg
  src/components/AboutAppsIconicCard/AboutAppsIconicCard.jsx
  src/components/AboutAppsIconicCard/AboutAppsIconicCard.style.jsx
  src/components/AboutAppsIconicCard/index.js
  src/components/index.js
  src/database/appsCoreValueCards.js
  src/database/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#38 #37 [FEAT] 홈페이지 내 `APPS 소식을 더 빨리 알고 싶다면` 섹션 구현
  public/images/socials/instagram-deactivate.svg
  public/images/socials/linkedin-active.svg
  src/components/SocialMediaLinkCards/SocialMediaLinkCards.jsx
  src/components/SocialMediaLinkCards/SocialMediaLinkCards.style.jsx
  src/components/SocialMediaLinkCards/index.js
  src/components/index.js
  src/database/socialMediaLinkCards.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#40 #39 [FEAT] 홈페이지 내 `함께 여정을 떠나볼까요?` 섹션 구현
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#42 #31 [FIX] homepage 내 import 오류 해결
  src/database/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: 🔧 Fix

#45 #43 [FEAT] `About APPS` 내 선 겹침현상 해결 및 그라데이션 모션 적용
  src/components/AboutAppsCoreValueCard/AboutAppsCoreValueCard.jsx
  src/components/AboutAppsCoreValueCard/AboutAppsCoreValueCard.style.jsx
  src/components/AboutAppsCoreValueCard/index.js
  src/components/AboutAppsIconicCard/index.js
  src/components/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: 🪄 Modify

#32 #30 [FEAT] Footer 기능 구현
  public/images/logo/logo-white.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.style.jsx
  src/components/MemberCard/MemberCard.jsx
  src/components/MemberCard/MemberCard.style.jsx
  src/components/MemberCard/index.js
  src/components/index.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
Labels: ✨ Feature

#46 #34 [FEAT] memberCard 클릭 시 모달 창 구현
  public/images/icons/divider.svg
  public/images/icons/x_orange.svg
  public/images/socials/linkedin.svg
  public/images/socials/tstory.svg
  src/components/MemberCard/MemberCard.jsx
  src/components/MemberCard/MemberCard.style.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/database/members.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
Labels: ✨ Feature, 🎨 UI

#50 #49 [FEAT] SNS active 효과 적용
  public/images/socials/instagram-activate.svg
  public/images/socials/linkedin-deactive.svg
  src/components/SocialMediaLinkCards/SocialMediaLinkCards.jsx
  src/database/socialMediaLinkCards.js
  src/pages/HomePage/HomePage.jsx
Labels: ✨ Feature

#52 #51 [FEAT] Header 상단에 고정
  src/components/Header/Header.style.jsx
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#57 #56 [FEAT] `부원들이 말하는 APPS` 섹션 구현
  public/images/character/character-blue.svg
  public/images/character/character-green.svg
  public/images/character/character-orange.svg
  public/images/character/character-pink.svg
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.jsx
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.style.jsx
  src/components/MemberFeedbackCardList/index.js
  src/components/index.js
  src/database/index.js
  src/database/memberFeedback.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#61 #58 [FEAT] 홈페이지 내 `프로젝트 목록` 섹션 구현
  src/components/ProjectCardList/ProjectCardList.jsx
  src/components/ProjectCardList/ProjectCardList.style.jsx
  src/components/ProjectCardList/index.js
  src/components/index.js
  src/database/index.js
  src/database/projectCategoryList.js
  src/database/projectList.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#62 #53 [FEAT] 홈페이지, about APPS 페이지 내 footer 적용 및 footer CSS 속성 일부 수정
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.style.jsx
  src/components/PageLayout/PageLayout.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#59 #44 [Feat] About 페이지 상단 구현
  src/database/activitiesCardList.js
  src/database/index.js
  src/database/styledSquareColorCards.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: ✨ Feature, 🛠️ Refactor

#65 #63 [FEAT] `부원들이 말하는 APPS` 섹션 구현
  src/components/Header/Header.style.jsx
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.jsx
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.style.jsx
  src/components/MemberFeedbackCards/MemberFeedbackCards.jsx
  src/components/MemberFeedbackCards/MemberFeedbackCards.style.jsx
  src/components/MemberFeedbackCards/index.js
  src/database/memberFeedback.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#67 #66 [MODIFY] `11기는 어떤 활동을 하였나요?` 내 문구 수정
  public/images/activities/about_BSproject.jpg
  public/images/activities/about_DevTalk.jpg
  public/images/activities/about_MT.jpg
  public/images/activities/about_basicstudy.jpg
  public/images/activities/about_exhibition.jpg
  public/images/activities/about_normalstudy.jpg
  public/images/activities/about_picnic.jpg
  public/images/activities/about_teamproject.jpg
  public/images/activities/activity_bs_project.png
  public/images/activities/activity_bs_study.png
  public/images/activities/activity_dev_talk.png
  public/images/activities/activity_exhibition.png
  public/images/activities/activity_mt.png
  public/images/activities/activity_normal_study.png
  public/images/activities/activity_picnic.png
  public/images/activities/activity_team_project.png
  src/components/ActivityCard/ActivityCard.style.jsx
  src/components/CalendarCard/CalendarCard.jsx
  src/components/CalendarCard/CalendarCard.style.jsx
  src/database/MonthlyActivityList.js
  src/database/activityCardList.js
  src/database/activityList.js
  src/database/index.js
  src/pages/AboutAppsPage/AboutAppsPage.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: 🪄 Modify

#69 #68 [FEAT] Header, Footer, 홈화면 반응형 구현
  src/components/AboutAppsCoreValueCard/AboutAppsCoreValueCard.style.jsx
  src/components/Header/Header.style.jsx
  src/components/MemberFeedbackCardList/MemberFeedbackCardList.style.jsx
  src/components/ProjectCardList/ProjectCardList.style.jsx
  src/components/SocialMediaLinkCards/SocialMediaLinkCards.style.jsx
  src/database/MonthlyActivityList.js
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: ✨ Feature

#73 #70 [FEAT] About 페이지 상단, 활동, 달력 섹션 반응형 구현
  src/components/ActivityCard/ActivityCard.style.jsx
  src/components/CalendarCard/CalendarCard.style.jsx
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
Labels: ✨ Feature, 🎨 UI

#79 #78 [FIX] 배포 이슈 해결을 위한 파일 추가
  public/_redirects
Labels: 🔧 Fix

#80 [MERGE] dev to main
  README.md
  public/_redirects
  public/images/thumbnails/img-thumbnail-1.png
  src/components/ActivityCard/ActivityCard.style.jsx
  src/components/CalendarCard/CalendarCard.style.jsx
  src/components/Footer/Footer.style.jsx
  src/components/ProjectCardList/ProjectCardList.jsx
  src/components/ProjectCardList/ProjectCardList.style.jsx
  src/database/projectList.js
  src/pages/AboutAppsPage/AboutAppsPage.style.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: 🌏 Deploy

#83 [MERGE] dev to main
  netlify.toml
Labels: 🌏 Deploy
